### ISSUE TITLE
[Jupyter] Notebook not showing any output

### ISSUE THREAD

**Issue by mobiledevver** [facebook/iTorch#34]
I am having the exact same problem as reported by -
https://github.com/facebook/iTorch/issues/24

In summary, 

When I launch `itorch notebook`, open a new notebook, and enter a trivial command like `1+1` followed by `shift-return`, the the cell hangs indefinitely with an * next to it. 

I am running on Ubuntu 12.04

I tried installing the very latest bits.  `ipython` works for me and `itorch` does work from the console - I get the `IN` prompt

Any ideas would be greatly appreciated.

**Comment by soumith** [comment]
what is your ipython version?

ipython --version

make sure that it is above 2.3

**Comment by mobiledevver** [comment]
Thanks for the response.  
The ipython version is 3.0.0

**Comment by soumith** [comment]
awesome, i have a reproduction. never tried itorch before with 3.0.0, looking into what fixes are needed

**Comment by soumith** [comment]
Sorry for the delay. I've fixed it via this commit: https://github.com/facebook/iTorch/commit/59be6bcaf64f737a2361158b3021923e1afde39f

All you have to do to get it working with IPython 3.0 is do:
```
luarocks install itorch
```

And then to start itorch in notebook mode:
```
itorch notebook
```
And then create a new iTorch notebook from dropdown menu.

starting `ipython notebook` wont work, starting `itorch notebook` will work.
I am looking to see how `ipython notebook` will also work in 3.0.
If after this reinstall, you are still having trouble in ipython v3.0, please reopen this issue.

**Comment by mobiledevver** [comment]
Thanks for the fix.  Unfortunately, still doesn't work for me.  Again, the console works fine.
